config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    
  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #Blog
  mount KepplerBlog::Engine, :at => '/', as: 'blog'
  #ContactUs
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'
end

app/models/keppler_contact_us/message.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerContactUs
  class Message < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    validates_presence_of :name, :email
    
    after_commit on: [:update] do
      __elasticsearch__.index_document
    end

    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:name, :subject, :create_at, :email, :read] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        name:  self.name,
        subject:  self.subject,
        email:  self.email,
        content:  self.content,
        read:  self.read ? "si--leidos" : "no--leidos",
        created_at:  self.created_at.to_s,
      }.as_json
    end

  end
  #Message.import
end

app/controllers/keppler_contact_us/application_controller.rb
module KepplerContactUs
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/keppler_contact_us/messages_controller.rb
#Generado con Keppler.
require_dependency "keppler_contact_us/application_controller"

module KepplerContactUs
  class MessagesController < ApplicationController  
    before_filter :authenticate_user!, except: [:create]
    layout 'admin/application', except: [:new]
    load_and_authorize_resource except: [:create]
    before_action :set_message, only: [:show, :edit, :update, :destroy]

    # GET /messages
    def index
      messages = Message.searching(@query).all
      @objects, @total = messages.page(@current_page), messages.size
      redirect_to messages_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /messages/1
    def show
      message = Message.find_by(id: params[:id])
      message.update(read: true) unless message.read
    end

    # POST /messages
    def create
      @message = Message.new(message_params)
      if verify_recaptcha(model: @message, timeout: 10, message: "Oh! Error con el reCAPTCHA!") and @message.save
        ContactMailer.contact(message_params).deliver
        redirect_to KepplerContactUs.redirection, notice: 'Mensaje enviado exitosamente.'
      else
        redirect_to KepplerContactUs.redirection, alert: 'Error: Revise los campos del formulario.'
      end
    end

    # PATCH/PUT /messages/1
    def update
      if @message.update(message_params)
        redirect_to @message, notice: 'Message was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /messages/1
    def destroy
      @message.destroy
      redirect_to messages_url, notice: 'Mensaje eliminado satisfactoriamente.'
    end

    def destroy_multiple
      Message.destroy redefine_ids(params[:multiple_ids])
      redirect_to messages_path(page: @current_page, search: @query), notice: "Mensajes eliminados satisfactoriamente" 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_message
        @message = Message.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def message_params
        params.require(:message).permit(:name, :subject, :email, :content, :read)
      end
  end
end

app/views/keppler_contact_us/messages/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.email.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 
			= t("model.#{controller_name.singularize}.description.title")
		%p 
			= t("model.#{controller_name.singularize}.description.body")
	

app/views/keppler_contact_us/messages/_form.html.haml
.contact-form

	= simple_form_for @message, :url => "/admin/messages", :method => :post do |f|
		.row
			.col-lg-12
				= f.input :name, label: false, wrapper: :bootstrap, input_html: {class: "form-control", placeholder: "Nombre", required: "required"}

			.col-lg-12
				= f.input :email, as: :email, label: false, input_html: {class: "form-control", placeholder: "Email", required: "required"}

			.col-lg-12
				= f.input :subject, label: false, input_html: {class: "form-control", placeholder: "Asunto"}

			.col-lg-12
				= f.input :content, as: :text, label: false, input_html: {class: "form-control", placeholder: "Mensaje..."}
		.row
			.col-lg-6.col-md-6.col-sm-6.col-xs-12
				.pull-left
					= raw recaptcha_tags :display => { :theme => 'custom', lang: 'es' }, ajax: true

			.col-lg-6.col-md-6.col-sm-6.col-xs-12.form-actions
				= f.button :submit, "Enviar", class: "btn btn-primary", id: "btn-submit"

:javascript
	$('#btn-submit').attr('disabled', 'disabled');
	$( ".contact-form" ).mouseover(function () {
		contact_form();
	});
		$( ".contact-form" ).keyup(function() {
		contact_form();
	});
	
	function contact_form(){
		name = $('#message_name').val();
		email = $('#message_email').val();
		subject = $('#message_subject').val();
		content = $('#message_content').val();
		recaptcha = $('#g-recaptcha-response').val();

		if (name != "" && email != "" && subject != "" && content != "" && recaptcha != "" ){
			$('#btn-submit').removeAttr('disabled')
		}
	}

app/views/keppler_contact_us/messages/_index_show.html.haml
.listing-show-header
	.actions
		
	%h5
		= material_icon.md_24.email.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @message.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.subject")
			.display-value= @message.subject
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.email")
			.display-value= @message.email
		%hr
		.display-value{align: "justify"}= @message.content
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/keppler_contact_us/messages/_listing.html.haml
%tr{ id: "row-#{message.id}" }
	- if can? :destroy_multiple, KepplerContactUs::Message
		%td.item-check{style:"width: 10%"}
			= link_to "", message_path(message), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{message.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{message.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{message.id}" }

		%td{style:"width: 10%"}
			= link_to "", message_path(message, search: @query), remote: true, class: "show-row"
			%span.hide-on-small-and-down{id: "read-status-#{message.id}"}
				- if message.read
					= material_icon.md_18.done.css_class("md-dark") 
				- else
					= material_icon.md_18.email.css_class("md-dark") 
			%span.hide-on-med-and-up
				- if message.read
					= material_icon.md_18.done.css_class("md-dark") 
				- else
					= material_icon.md_18.email.css_class("md-dark") 
									
		%td{style:"width: 30%"}
			= link_to "", message_path(message, search: @query), remote: true, class: "show-row"
			%span
				= message.name
		%td.hide-on-small-and-down{style:"width: 30%"}
			= link_to "", message_path(message, search: @query), remote: true, class: "show-row"
			%span
				= message.subject
		%td.hide-on-small-and-down{style:"width: 30%"}
			= link_to "", message_path(message, search: @query), remote: true, class: "show-row"
			%span
				= message.created_at.strftime("%d/%m/%Y - %H:%M:%S")
	%td{style:"width: 5%"}		
		= link_to message_path(message), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/keppler_contact_us/messages/edit.html.haml
= title "Messages - editar | #{@message.id}"
= render 'form'

app/views/keppler_contact_us/messages/index.html.haml
= title("Messages - Listado")
.listing.col.l9.m12.s12
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |message|
				= render 'listing', message: message
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center							
							= t("model.#{controller_name.singularize}.no_found.text")

	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

app/views/keppler_contact_us/messages/new.html.haml
= title "Messages - Nuevo"
= render 'form'

app/views/keppler_contact_us/messages/show.html.haml
= title "Messages | #{@message.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, KepplerContactUs::Message
				= link_to message_path(@message), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: '¿Estás seguro de querer eliminar este mensaje?' } do
					= material_icon.md_18.delete.css_class("md-dark")
			= link_to messages_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @message.name.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.subject")
					.display-value.fs-body-1.tc-black-2= @message.subject.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.email")
					.display-value.fs-body-1.tc-black-2= @message.email.to_s.humanize
				%hr
				.display-value.fs-body-1.tc-black-2= @message.content.to_s.humanize

app/views/keppler_contact_us/messages/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@message.id}").addClass("active")
- if KepplerContactUs::Message.where({read: nil}).count > 0
	$("#badge-message").html("#{KepplerContactUs::Message.where({read: nil}).count}")
- else
	$("#badge-message").html("")
$('#read-status-#{@message.id}').html("<i class='mi md-18  md-dark'>done</i>");
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");